### ISSUE TITLE
Tag a Release, also add modules support?

### ISSUE THREAD

**Issue by mikesep** [AlekSi/gocov-xml#10]
Hi @AlekSi and other contributors,

First, thanks for making gocov-xml -- it's a very valuable tool for our Jenkins pipelines for Go projects!

Could you please tag a Release of this project? I ask because I've run into an issue with a Go modules proxy that comes up mainly because of the behavior of pseudo-versions, and I think the best long-term fix is to tag a release of this project, since it appears to be fairly stable at this point.

If you wanted to explicitly add Go modules support, that would be great too. 😄 It looks like it wouldn't be hard, so I don't think you'd need my help, but if you'd like me to prepare a PR, I can do that.

Thanks!

**Comment by mikesep** [comment]
👋 @AlekSi

**Comment by devtomnl** [comment]
@AlekSi this will be appreciated, since right now things are risking to break builds! :)

**Comment by eccles** [comment]
any chance that this will be fixed for gomodules - currently there appears to be no way of installing this due to recent changes in Go 1.1.6/7 refading using 'go install instead of go get - go install requires tagged versions..

**Comment by mikesep** [comment]
Hi @eccles, I don't think that's actually the case.

```console
$ GOBIN=$PWD go install github.com/AlekSi/gocov-xml@latest   # GOBIN=$PWD is optional
go: finding module for package github.com/axw/gocov
go: found github.com/axw/gocov in github.com/axw/gocov v1.0.0

$ go version -m gocov-xml
gocov-xml: go1.17.1
	path	github.com/AlekSi/gocov-xml
	mod	github.com/AlekSi/gocov-xml	v0.0.0-20190121064608-3a14fb1c4737	h1:JZHBkt0GhM+ARQykshqpI49yaWCHQbJonH3XpDTwMZQ=
	dep	github.com/axw/gocov	v1.0.0	h1:YsqYR66hUmilVr23tu8USgnJIJvnwh3n7j5zRn7x4LU=
```

**Comment by AlekSi** [comment]
Version 1.0.0 is out: https://pkg.go.dev/github.com/AlekSi/gocov-xml@v1.0.0 Sorry for the wait.

**Comment by mikesep** [comment]
Thanks very much!
