### ISSUE TITLE
Cobertura can't find sources

### ISSUE THREAD

**Issue by AlekSi** [AlekSi/gocov-xml#2]
In typical setup Cobertura will be unable to find sources, and correct setup is too complicated. I believe we can simplify it using `<sources>` element in XML.

**Comment by venkat4tech** [comment]
Hello,
Can we please merge the fix and close the issue ? Having source info along with coverage is vital to browse thru the report.

**Comment by abhijithda** [comment]
> Please rebase #4 to the current master, or send a new PR.

Here's the new PR #9.

**Comment by AlekSi** [comment]
Should be closed by #9.
